### ISSUE TITLE
Resolve all breaking changes and bottom-line refactors before the workshop

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#321]
Here is a list of issues we need to tackle before we can make the high-quality style guide workshop:
- [ ] Finish all pending discussions: #106 #174 #245 #127 #233 
- [ ] Component (row) with holes and wrapping: #104 
- [ ] Flexbox for layouting and components: #103 #299 
- [x] Deal with Icons: #118 #234 #127 
- [ ] Refactor some components: #305 #304 #322
